{% set name = "dreqpy" %}
{% set version = "1.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/dreqPy-{{ version }}.tar.gz
  sha256: 12192a9d93c13db499b7ba1d285c1f340fd8f4e9c5202f35b892d7b4543a74df

build:
  number: 1
  noarch: python
  entry_points:
    - drq = dreqPy.dreqCmdl:main_entry
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - lxml
    - requests
    - xlsxwriter

test:
  imports:
    - dreqPy
    - dreqPy.examples
  commands:
    - pip check
    - drq
    - python -c "from dreqPy import dreq; dq = dreq.loadDreq()"
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://proj.badc.rl.ac.uk/svn/exarch/CMIP6dreq/tags/01.00.33
  summary: CMIP6 Data Request Python API
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - zklaus
